### PR TITLE
Add plots to vignette example

### PR DESCRIPTION
**Pull request by Bisaloo**
This should look better once #10 is fixed and we can update the example to one with more entries. I wanted to provide plotting functions within the package at the beginning but I don't think it's a good idea. It's probably good enough to propose them to the users in the vignette.

### CODE REVIEW

**Comment by Bisaloo** [comment]
I'm sooo confused right now.

- policies can be:
    * can
    * cannot
    * restricted
    * unclear
    * unknown
    * NA
- colours can be
    * green
    * blue
    * yellow
    * gray
    * white
    * NA

I haven't seen this documented anywhere either. I'll have another look.

**Comment by Rekyt** [comment]
It is documented in the official documentation of the API.
Policies are detailed in Appendix B (but not the NA values?)
And colours are defined p. 11 of the same document.

**Comment by Bisaloo** [comment]
Actually, `NA` are just empty values. We're the ones converting them to `NA`.

**Comment by Bisaloo** [comment]
Should we convert `unknown` to NA?

**Comment by Bisaloo** [comment]
Documentation for colours: http://www.sherpa.ac.uk/romeo/definitions.php?la=en&fIDnum=|&mode=simple&version=#colours

`gray` is missing...

**Comment by Rekyt** [comment]
I'll do it in a separate PR for the moment the vignette is nice & simple enough.
Maybe at a point we should copy it in the `README.Rmd` file at the root of the repo.

**Pull request merged**
